<?php

/**
 * Helper function for #uiid default.
 */
function uiid_element_settings_default() {
  return array(
    'source' => '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ',
    'min' => 4,
    'max' => 4,
    'generate' => TRUE,
    'revisable' => TRUE,
    'unique_callback' => NULL,
    'generate_callback' => 'uiid_generate',
  );
}

/**
 *  Implements hook_element_info().
 */
function uiid_element_info() {
  $elements['uiid'] = array(
    '#default_value' => '', // Initiate ['uiid']['value']
    '#input' => TRUE,
    '#process' => array('uiid_element_process'),
    '#theme' => array('uiid_field'),
    '#theme_wrappers' => array('form_element'),
    '#tree' => TRUE,
    '#element_validate' => array('uiid_element_validate'),
    // Custom properties
    '#uiid' => uiid_element_settings_default(),
  );
  return $elements;
}

/**
 * Process callback for uiid element.
 */
function uiid_element_process($element, $form_state, $complete_form) {
  // Send in #uuid defaults, while sub properties are not automatically being inserted.
  $element['#uiid'] += uiid_element_settings_default();

  // Unique #id
  $id = 'uiid-' . sha1(implode('-', $element['#parents']));
  $element['value'] = array(
    '#type' => 'textfield',
    //'#required' => $element['#required'],
    '#title' => t('UIID'),
    '#title_display' => 'invisible',
    '#theme_wrappers' => array(),
    '#prefix' => '<span id="' . $id . '">',
    '#suffix' => "</span>",
    '#required' => $element['#required'],
  );
  if (isset($element['#default_value'])) {
    $element['value']['#default_value'] = $element['#default_value'];
    if (!$element['#uiid']['revisable']) {
      $element['value']['#disabled'] = TRUE;
    }
  }

  if ($element['#uiid']['generate']) {
    $element['generate'] = array(
      '#type' => 'button',
      '#name' => str_replace($id, '-', '_') . '_generate',
      '#value' => t('Generate'),
      '#ajax' => array(
        'callback' => 'uiid_generate_ajax',
        'wrapper' => $id,
      ),
      '#limit_validation_errors' => array(),
    );
  }

  return $element;
}

/**
 * Element validate callback.
 */
function uiid_element_validate($element, &$form_state) {
  if ($form_state['submitted'] && !uiid_unique($element, $form_state)) {
    form_set_error($element['#name'], t('UIID need to be unique.'));
  }
}

/**
 * Ajax callback.
 */
function uiid_generate_ajax($form, $form_state) {
  $element = uiid_form_get_element($form, $form_state);
  if (function_exists($element['#uiid']['generate_callback'])) {
    $generate_callback = $element['#uiid']['generate_callback'];
  }
  else {
    $generate_callback = 'uiid_generate';
  }
  $element['value']['#value'] = $generate_callback($element, $form_state);
  // @todo Limit tries times, then set error.
  while (!uiid_unique($element, $form_state)) {
    $element['value']['#value'] = $generate_callback($element, $form_state);
  }

  return $element['value'];
}

/**
 * Helper function to get the element for ajax callback.
 */
function uiid_form_get_element($form, $form_state) {
  $array_parents = $form_state['triggering_element']['#array_parents'];
  // Remove the 'generate'.
  $array_parents = array_slice($array_parents, 0, -1);
  $element = drupal_array_get_nested_value($form, $array_parents);

  return $element;
}

/**
 * Value callback for uiid element.
 */
function form_type_uiid_value($element, $input = FALSE, &$form_state) {
  if ($input !== FALSE) {
    return $input;
  }
  elseif (!empty($element['#default_value'])) {
    return array(
      'value' => $element['#default_value']
    );
  }

  return;
}

/**
 *  Implements hook_theme().
 */
function uiid_theme($existing, $type, $theme, $path) {
  return array(
    'uiid_field' => array(
      'render element' => 'element',
    ),
  );
}

/**
 * Theme function for 'uiid_field'.
 *
 * Should this exist?
 */
function theme_uiid_field($variables) {
  $element = $variables['element'];
  $output = '';
  $output .= drupal_render($element['value']);
  $output .= "";
  $output .= drupal_render($element['generate']);

  return $output;
}

// =============================================================================
// Utility

/**
 * Helper function to generate uiid.
 */
function uiid_generate($element, $form_state) {
  extract($element['#uiid']);
  $len = mt_rand($min, $max);
  $ret = '';
  $rand_max = strlen($source) - 1;
  for ($i = 0; $i < $len; $i++) {
    $ret .= $source[mt_rand(0, $rand_max)];
  }

  return $ret;
}

/**
 * Helper function to check uiid uniqueness.
 */
function uiid_unique($element, $form_state) {
  $unique_callback = isset($element['#uiid']['unique_callback']) ? $element['#uiid']['unique_callback'] : NULL;
  if (function_exists($unique_callback)) {
    if (!$unique_callback($element['value']['#value'], $element, $form_state)) {
      return FALSE;
    }
  }

  return TRUE;
}
